### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ArchieCoder** [computesam/Tesla-Demo#1]
Hi, I saw your comment about Brad's comment regarding Parallels and I saw your app is about Tesla. I'm a owner too.

![image](https://user-images.githubusercontent.com/1608424/176728496-29d11f47-71fe-4196-8549-2556b651c7fc.png)

**Comment by computesam** [comment]
Thanks for the update! It seems the upload missed some pretty necessary files😄

Will update as soon as I can and marked resolved once I confirm the source code is all there!

**Comment by computesam** [comment]
# Thank You Archie!
## My testing has concluded that this problem is now solved 🥳
I have looked into this further and updated the Repo with a Patch Release.
Thanks for bringing this to my attention and if you have any further questions or problems please reach out!
